export interface Posting {
    _id: string,
    business_name: string,
    job_title: string,
    timezone: string,
    field: string,
    country: string,
    created_date: Date,
    description: string,
    salary: string,
    start_date: Date,
    isContract: Boolean,
    contract_length_in_months: Number,
    isRenewable: Boolean,
    isPromoted: Boolean,
    requirement: string,
}